network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp-identifier: mac
      addresses:
        - 192.168.3.1/24
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
    usb0:
      dhcp4: no
      addresses:
        - 192.168.2.1/24
      gateway4: 192.168.2.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
    usb1:
      dhcp4: no
      addresses:
        - 192.168.2.1/24
      gateway4: 192.168.2.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]