network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 10 # <--- LOWEST METRIC = HIGHEST PRIORITY
      dhcp-identifier: mac
      addresses:
        - 192.168.3.1/24
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
    usb0:
      dhcp4: no
      addresses:
        - 192.168.2.1/24
      routes:
        # We are intentionally setting a high metric to DEPRIORITIZE this route
        - to: default
          via: 192.168.2.1
          metric: 200 # <--- HIGHER METRIC = LOWEST PRIORITY (Fallback)
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
    usb1:
      dhcp4: no
      addresses:
        - 192.168.2.1/24
      routes:
        # We are intentionally setting a high metric to DEPRIORITIZE this route
        - to: default
          via: 192.168.2.1
          metric: 201 # <--- HIGHER METRIC = LOWEST PRIORITY (Fallback)  
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]